//------------------------------------------------------------------------------
// <auto-generated>
//     Gerado a partir de AppStrings.resx pelo mesmo layout que o Custom Tool
//     "PublicResXFileCodeGenerator" do Visual Studio produziria. Escrito à mão porque o ambiente
//     de build deste repositório (dotnet CLI, sem Visual Studio) não roda o single-file generator -
//     ver "Como ver os apontamentos sem o SonarCloud" no claude-context.md para o mesmo tipo de
//     limitação. Regenerar manualmente (mesma lista de <data name="..."> do .resx, uma propriedade
//     por chave) sempre que uma chave for adicionada, removida ou renomeada em AppStrings.resx.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable disable

namespace GDSB.MAUI.ViewModels.Resources
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    public class AppStrings
    {
        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        public AppStrings()
        {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GDSB.MAUI.ViewModels.Resources.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }

        public static string Unlock_HowItWorks => ResourceManager.GetString("Unlock_HowItWorks", resourceCulture);

        public static string Unlock_HowItWorksDescription => ResourceManager.GetString("Unlock_HowItWorksDescription", resourceCulture);

        public static string Unlock_Tagline => ResourceManager.GetString("Unlock_Tagline", resourceCulture);

        public static string Unlock_VaultFileLabel => ResourceManager.GetString("Unlock_VaultFileLabel", resourceCulture);

        public static string Unlock_ChooseFileButton => ResourceManager.GetString("Unlock_ChooseFileButton", resourceCulture);

        public static string Unlock_ChangeFileButton => ResourceManager.GetString("Unlock_ChangeFileButton", resourceCulture);

        public static string Unlock_MasterPasswordLabel => ResourceManager.GetString("Unlock_MasterPasswordLabel", resourceCulture);

        public static string Unlock_PasswordPlaceholder => ResourceManager.GetString("Unlock_PasswordPlaceholder", resourceCulture);

        public static string Unlock_BiometricConfiguredForLabel => ResourceManager.GetString("Unlock_BiometricConfiguredForLabel", resourceCulture);

        public static string Unlock_UnlockWithBiometricButton => ResourceManager.GetString("Unlock_UnlockWithBiometricButton", resourceCulture);

        public static string Unlock_ChangeVaultButton => ResourceManager.GetString("Unlock_ChangeVaultButton", resourceCulture);

        public static string Unlock_CreateVaultLink => ResourceManager.GetString("Unlock_CreateVaultLink", resourceCulture);

        public static string Unlock_RecoverBackupLink => ResourceManager.GetString("Unlock_RecoverBackupLink", resourceCulture);

        public static string Unlock_LanguagePickerDescription => ResourceManager.GetString("Unlock_LanguagePickerDescription", resourceCulture);
    }
}
